name: twilio_programmable_video_web
description: A web implementation of the Twilio Programmable Video Plugin.
version: 1.0.0-alpha.1
homepage: https://gitlab.com/twilio-flutter/programmable-video
repository: https://gitlab.com/twilio-flutter/programmable-video/-/tree/master/programmable_video_web
issue_tracker: https://gitlab.com/twilio-flutter/programmable-video/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  twilio_programmable_video_platform_interface:
    path: ../programmable_video_platform_interface
  js: ^0.6.3
  enum_to_string: ^2.0.1
  dartlin: ^0.6.1
  version: ^2.0.0
  collection: ^1.15.0

dev_dependencies:
  pedantic: ^1.8.0+1

flutter:
  plugin:
    platforms:
      web:
        pluginClass: ProgrammableVideoPlugin
        fileName: twilio_programmable_video_web.dart
